---
output: html_document
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->
<!-- the font size is scaled to 90% to match text -->

```{=html}
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {
    extensions: ["[Contrib]/mhchem/mhchem.js"]
}
});
MathJax.Hub.Config({ 
        "HTML-CSS": { scale: 90 }, 
        SVG: { linebreaks: { automatic:true } }, 
 });
</script>
```

<!-- text for activity 1 -->

An important tool for implementing a sampling strategy is a grid that divides the the bulk sample into smaller units from which we may draw individual samples. The sampling grid on the right, for example, has 324 cells arranged in 18 rows and in 18 columns that may represent either spatial, temporal, or physical information. The controls above the grid allow you to explore where samples are collected (random vs. stratified) from how many sites to collect samples. In a random sampling, every site is equally likely to be selected; in a stratified sampling, the sites or samples are divided into two or more groups (called strata) and sampled in a way that maintains their relative proportion to each other.

**Exercise 1**. Propose 3--5 examples of analytical problems where the basic sampling grid is useful. Here is an example to get you started: you could overlay the grid on an agricultural field to define where to gather samples for a study to determine the amount of nitrogen in the field following the application of fertilizer.

**Exercise 2**. For a random sampling, the slider allows you to choose how many individual sites (cells) you will sample. The mean and the standard deviation for the samples are displayed above the grid and individual results are given in the grid both numerically and visually. How are the mean and the standard deviation affected by the number of samples you analyze?

**Exercise 3**. For a stratified sampling, the sampling grid is divided into three groups (strata), and samples are collected randomly from within each stratum. The slider sets the number of samples for the smallest of the three strata. When the slider is set to 3, how many samples will you collect from each of the strata? Why does this relationship make sense?

**Exercise 4**. For a stratified sampling, the mean and the standard deviation of the strata are listed in the order smallest stratum/intermediate stratum/largest stratum; the overall mean is listed below the grid. The results for individual samples appear in the grid both numerically and visually. How are the mean and the standard deviation affected by the number of samples? How do they compare to a random sampling. 

**Exercise 5**. For a stratified sampling, set the number of sites to 10 and show that the individual means for the three strata are consistent with the overall mean.
